# @package _global_
defaults:
  - override /data: vae
  - override /optimizer: default
  - _self_

data:
  num_workers: 0
  batch_size: 8
  n_samples: 256

optimizer:
  epochs: 5

is_local_run: True
device: "cpu"
